### ISSUE TITLE
Allow screenshots on mobile in incognito mode

### ISSUE THREAD

**Issue by malihanda** [mdirolf/crosshare#272]
Desired behavior: Take a screenshot of an incomplete puzzle in incognito mode. (This is good for promoting a puzzle that I post, [eg link](https://twitter.com/malisolves/status/1386729279459926016))

Actual behavior: My phone (Pixel 4, using the Chrome app) won't let me take a screenshot of an embedded puzzle, or a puzzle on the Crosshare site while in incognito mode. I can take a screenshot of an incomplete puzzle on the Crosshare site while not in incognito mode. I wasn't able to test the not-incognito / embedded puzzle case.

**Comment by mdirolf** [comment]
What happens when you try to take a screenshot? Is it possible chrome disables screenshots for any website while in incognito - can you try some random website and see if you get the same behavior?

**Comment by mdirolf** [comment]
@malihanda any chance you can post some more details here? Otherwise I'm going to close this - I can't think of anything Crosshare is doing that would disable screenshots.
