### ISSUE TITLE
Move "Unfinished Solves" and "Your Constructions" from Account page

### ISSUE THREAD

**Issue by JaclyneOoi** [mdirolf/crosshare#281]
This can get broken down into multiple issues, but I figured I'd get thoughts on these design ideas grouped together.

Most of the content on the Account page is related to settings, so Unfinished Solves and Your Constructions feel out of place.

One idea I've come up with is to restructure things so that Crosshare has 3 main sections, which I think create logical places for different categories of features/functionality to live:
1) Homepage
2) Construction zone (or some better name)
3) Account

**Here's a [rough prototype on Figma](https://www.figma.com/proto/RsDBEdrU0q2TjUiZH6Bjf4/Crosshare?page-id=11%3A0&node-id=102%3A2818&viewport=-805%2C706%2C0.3189340829849243&scaling=scale-down-width&hide-ui=1)**
**and a [site map](https://www.figma.com/file/CiZPYjhgeYGtE0St52Fioi/Site-map?node-id=0%3A1) roughly outlining how different pages are related to each other**

<hr />

### Homepage
* This is your starting point when you want to find puzzles to solve
* Mock below includes a new section for non-featured puzzles (as per https://github.com/mdirolf/crosshare/issues/276) and a section for unfinished solves (moved from the Account page)
* Unfinished solves would only be shown to people who are signed in

<img width="500" alt="image" src="https://user-images.githubusercontent.com/5751369/119269236-9acc5a80-bbc4-11eb-9317-238ac6a7cb1d.png">

<hr />

### Construction zone
* This is a new homebase for puzzle construction
* Includes your constructions, moved from the Account page
* This is where future construction-related features could live, like overall stats about your puzzles or draft puzzles if those were things people wanted
* This section could maybe be hidden for users who aren't signed in

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5751369/119269525-1da1e500-bbc6-11eb-8faa-541c8800c6db.png">

<hr />

### Account
* This page is only about settings, now that Unfinished Solves and Your Constructions live elsewhere
* More cleanup can be done here to group different kinds of settings, especially as new ones are added like preferences for the puzzle solving UI

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5751369/119269546-3d390d80-bbc6-11eb-96ee-117e05577654.png">

**Comment by mdirolf** [comment]
I love everything about this! Thanks @JaclyneOoi 😊

**Comment by mdirolf** [comment]
I think this can sort of be broken up and done/deployed in chunks over time. I've started by creating nicer buttons for construct/upload to match your design and layout @JaclyneOoi - I think it's a big improvement already!

**Comment by mdirolf** [comment]
The only thing I'm not sure I love is the name for the "Construction Zone". I do love the idea in general - I've been thinking about adding some overall stats for constructors and this would be a perfect place for it.

Maybe "constructor home"? Any other ideas?

**Comment by JaclyneOoi** [comment]
* Constructor Corner
* Constructor Dashboard
* Your Constructions (even if more content were added to this section, like stats, it'd still be about your own constructions)

**Comment by mdirolf** [comment]
I think Constructor Dashboard is great

**Comment by mdirolf** [comment]
I believe this is all done and deployed 🎊. Please LMK if you notice anything I missed or any issues.

Thanks again @JaclyneOoi - I'm already looking forward to your next set of ideas. I especially appreciated how you kept the design changes incremental which made it easy to get out the door.

**Comment by JaclyneOoi** [comment]
Thanks @mdirolf, you're so fast! The only other thing I was thinking of was that the "Older unfinished solves" link could go to a dedicated Unfinished Solves page, similar to how the links in the Daily Mini and Featured Puzzles sections work.
