### ISSUE TITLE
Save previous play data with account

### ISSUE THREAD

**Issue by glasser** [mdirolf/crosshare#288]
If you log in to the app for commenting, it would nice if previous play data could be synced as well (maybe optionally?). eg, as a 7xwords fan, I sometimes do it on my computer and sometimes on my phone, and it would be nice if it were easy for me to see when I go to a puzzle if I've done it at all, vs just if I've done it on that device.

**Comment by mdirolf** [comment]
This should already be working if you're logged in with the same account both places. Is it not working for you?

I have occasionally noticed issues when I start a puzzle on two devices and then finish on one - I believe there are some syncing edge cases - but generally it seems to work well.

The only other thing I can think of is that I vaguely remember some issues w/ localstorage in certain browsers (FF maybe?) when in private browsing mode and iframed (like on 7xwords). We use LS as a kind of write-through cache for play state so perhaps that could be causing some issues.

**Comment by glasser** [comment]
Oh huh. Maybe I wasn't logged in on both places :) Looking good now!
