### ISSUE TITLE
Make login status more obvious on embedded welcome screen

### ISSUE THREAD

**Issue by glasser** [mdirolf/crosshare#302]
When crosshare is embedded (eg on 7xwords) and I open a puzzle that I don't remember if I've done it and it says I haven't, I can't tell if that's because I've gotten logged out or because I actually haven't done it. It would be great if the title screen told me if I was logged in or not and gave me a login link.

(I also don't know why I seem to get logged out frequently on my phone but that's a different issue I guess!)

**Comment by mdirolf** [comment]
Great idea!

**Comment by glasser** [comment]
Awesome!

(Any thoughts on what I can do to debug the fact that I seem to be logged out on my Android browser a lot whereas my Mac Chrome stays logged in indefinitely?)

**Comment by mdirolf** [comment]
@glasser that's very strange - unfortunately all auth state persistence is handled by the firebase library we're using and I'm not sure that there's much I can configure on crosshare's end. Do you notice the same frequent log-outs on crosshare.org or is it only when loading embedded puzzles? I'm wondering cross-domain cookies are getting cleared more aggressively by your browser or something like that

**Comment by glasser** [comment]
I mostly just see it when looking embedded on 7xwords.  Then I click through to crosshare.org to log in over there.

**Comment by mdirolf** [comment]
I've noticed a couple of people running into auth hiccups recently, especially for embeds, as browsers roll out more aggressive anti-tracking behavior. Obviously crosshare is using iframes to provide embedded functionality, not to track users, but to the browsers I think it pretty much looks the same. I'm going to have to do some more research to see if there is anything we can change to make it clear to browsers that we're not the bad guys :rofl: - any suggestions or ideas are welcome!
