### ISSUE TITLE
New basic tools for constructor

### ISSUE THREAD

**Issue by Devagio** [mdirolf/crosshare#329]
A very helpful feature which will take minutes to add:
Allow constructors to highlight / colour squares temporarily while constructing crosswords. This can be very useful to keep a track of bottlenecks. 
Additionally, adding comments for each square could be a greatly useful.

Advanced tool:
Allow for selecting certain parts of the crossword and apply autofill only in the selected regions. The selected region can be treated as a crossword itself, and it is upto the constructor to not select partial words. This will significantly speed up construction process.

Another possibility is to have private dictionaries for each account where new words can be added. People from various regions can make great use of this feature to blend in english with their own language / names / characters / etc. This however may need some consideration in way of word-priority.

**Comment by mdirolf** [comment]
Hi - there are already issues for some of these:
#140 - autofill partial grd
#109 - custom word lists / dictionaries

As for highlighting - you can already highlight/shade certain a cell using the 'more' menu or the ` key - does that do the trick for you?

**Comment by Devagio** [comment]
It does.
Apologies for not being able to find other similar issues.

**Comment by mdirolf** [comment]
@Devagio Glad that works - no apologies necessary I appreciate the ideas!
