### ISSUE TITLE
Switch meta puzzle from "delay reveal by a week" to "reveal answer instantly" once the puzzle has been published

### ISSUE THREAD

**Issue by malihanda** [mdirolf/crosshare#339]
I don't see a way to change this.

**Comment by mdirolf** [comment]
Yup it's not available on the edit page yet. In the meantime if you need to change one just LMK (here or via email/twitter) and I can manually update.

Closing as a duplicate of https://github.com/mdirolf/crosshare/issues/331

**Comment by malihanda** [comment]
Can you update this one pls to be instant reveal: https://www.7xwords.com/daily/11/11-09.html

**Comment by mdirolf** [comment]
Shuold be updated once the cache clears in ~1hr or less
