### ISSUE TITLE
Barred grids

### ISSUE THREAD

**Issue by sus1d1p** [mdirolf/crosshare#340]

**Comment by mdirolf** [comment]
Yeah I like this idea - honestly never solved a puzzle that used those but I think it makes sense to support it. Possibly related to #304 if either of those formats support them

**Comment by mdirolf** [comment]
Use `,` as hotkey to add a bar after current cell

**Comment by mdirolf** [comment]
Still to do:
- [ ] tests
- [ ] add bar button in constructor more menu
- [ ] rerun autofiller when a bar is added/removed (need to somehow distinguish from prior solves)
- [ ] print bars in PDF
