### ISSUE TITLE
!@ present in comment references

### ISSUE THREAD

**Issue by jjmacosko** [mdirolf/crosshare#360]
When a clue has "!@" in it in order to avoid the cross-reference showing up (e.g. when someone wants to say "3D" without cross-referencing 3-Down) and someone else references that clue in a comment, the "!@" that is supposed to be invisible appears in the clue preview. This is a super minor thing; I'm more just testing the bug posting in Github, so let me know if this is the wrong place for it. Example shown in image below.
<img width="220" alt="Screen Shot 2021-12-18 at 7 40 08 PM" src="https://user-images.githubusercontent.com/96359447/146659378-63119cd7-2139-452c-9c70-85600c02968e.png">

**Comment by mdirolf** [comment]
Good catch! And this is definitely the correct place to post, thanks 😊.

When doing this it's worth making sure that it's correctly removed from meta description tags if it's not already, too.
