### ISSUE TITLE
Bars don't show up in puzzle previews

### ISSUE THREAD

**Issue by jjmacosko** [mdirolf/crosshare#361]
The thumbnail of grids with only bars and no black squares will appear as an empty grid. Not sure if this is by design or a bug. See image below.
<img width="283" alt="Screen Shot 2021-12-19 at 10 17 21 PM" src="https://user-images.githubusercontent.com/96359447/146706795-9fb5d9a7-a7ee-4ab6-9cc9-db2cfe98899f.png">

**Comment by mdirolf** [comment]
Thank you for opening this! I noticed this earlier and forgot to open an issue for it
