### ISSUE TITLE
Feature Request: Better wordlist usage for autofill

### ISSUE THREAD

**Issue by jjmacosko** [mdirolf/crosshare#362]
I believe the spreadthewordlist to be better scored than the currently used Broda list. Since we now know we have permission to use the spreadthewordlist (see attached image), here is my suggestion for the four tiers. 

Tier 3: 50 and up on spreadthewordlist. 
Tier 2: 40 and up on spreadthewordlist plus all the names from Erica's name list. 
Tier 1: 30 and up on spreadthewordlist plus 50 and up on untrimmed Broda. 
Tier 0: Everything else on spreadtheworldlist and untrimmed Broda. 

If anybody has any better ideas for the tiers or knows how to get permission from Mark Diehl for his trimmed Broda list please share!
<img width="828" alt="Screen Shot 2021-12-22 at 4 57 37 PM" src="https://user-images.githubusercontent.com/96359447/147160141-badf50bb-e0ca-4aaf-a70b-5b343b478dee.png">

**Comment by mdirolf** [comment]
Awesome, thanks @jjmacosko - I edited your post just to use the same numbers for the tiers that crosshare uses in the codebase so my brain won't be doing conversions back and forth as I type 😂.

As a reference, here is how things work currently:

Tier 3: 80 and up on untrimmed Broda
Tier 2: 60 and up on untrimmed Broda, appears in ginsbergs clue database at least 3 times in shortz era puzzles (or 15 times in other puzzles)
Tier 1: 50 and up on untrimmed Broda, Erica's name list, appears in clue database at least once in shortz era (or 5 times in other puzzles)
Tier 0: Everything else on untrimmed Broda

**Comment by jjmacosko** [comment]
Thanks for the edit @mdirolf ! And if that's the case you can drop Erica's name list down to Tier 1 and add in the ginsberg clue database to the tiers (I don't want you to have to change the current rankings more than you have to lol). Do you know does the ginsberg database take out nonsense theme answers that just appeared once in NYT?

**Comment by mdirolf** [comment]
Yeah it's actually crosshare that filters those out, but we do remove themers from it.
