### ISSUE TITLE
Cannot see full list of followers

### ISSUE THREAD

**Issue by eoxford** [mdirolf/crosshare#375]
If I look at my blog https://crosshare.org/damefoxwords, it says I have 17 followers. However, if I actually click to see the list, I can only see 9. Zooming out/trying to scroll does nothing.

I suppose the issue could also be that I only have 9 followers and it's mistakenly saying 17 for some reason. One of the two.

I also checked a more popular constructor (https://crosshare.org/sommersmith) to see if the issue persists. Their page says they have 45 followers. If you click on the list though, it only shows 25. The issue does not seem to exist for the list of blogs someone is follow_ing_. sommersmith is following 48 constructors, and all 48 of them appear if you click to see the list.

**Comment by mdirolf** [comment]
This is actually as designed but I recognize how confusing it is - open to any and all suggestions for improvement. Here's what's happening:

Most "users" of Crosshare don't have a username / blog set up - they've just signed in before to leave some comments, follow some constructors, or even post puzzles of their own. So the followers count shows the total number of followers, including those that don't have a username. When you click through to the list, though, Crosshare only shows you the users who actually have a page to click on.

Obviously for follow_ing_ this dichotomy doesn't exist - you can only follow somebody if they have a page set up so the count matches the list exactly.

I guess the options are:

- Keep the current behavior but try to add a note somewhere to explain what's going on
- Update the count to include only those followers who have blogs/usernames

Any other ideas for a better solution?

**Comment by eoxford** [comment]
Ah, interesting. That makes sense. Of the two solutions you propose, I prefer the first one. Could add a note at the top when you click on the list, or maybe something at the bottom saying "X followers don't have usernames."

However, it does occur to me that being able to follow someone on the internet without them having any way of identifying you, not even a made-up username, is not good. I don't think Crosshare is particularly in danger of having users stalked by anyone, but just on principle, if there was ever a problem with a particular user, it's not great that people can't tell if that user is following them. Many websites have rules that you cannot interact with the site until you log in and are identifiable to others on the site. It might be better if, when someone tried to follow a blog for the first time, a prompt came up asking them to create a Crosshare username. If we could de-couple having a username from having a blog page, so that everyone has a username but not everyone necessarily has to have a blog, that would be good, but I don't know how feasible that is.

**Comment by mdirolf** [comment]
I think I came to the same conclusion that option 1 is better - I think maybe a note at the top of the list that says "X followers have Crosshare blogs:" would suffice. I'll try to get that out in the next deploy!

Hmm that's definitely a concern I hadn't considered. I think the risk of bad behavior from following in its current form is pretty low - all it's doing is saying "notify me when this constructor posts a public puzzle", i.e. there is nothing at all different about it from somebody just going to your blog page and refreshing it once a day. But your point is definitely worth keeping in mind if there are any changes or additions to the nature of "following" on Crosshare.

I think your proposed solution (forcing followers to register a username) is a good one, too, if we decide it needs to be addressed. My gut feeling for now, though, is that there isn't really any risk of abuse and so it's not worth adding friction and making folks less likely to follow. One goal for the site is to get as many solvers as possible for constructors, and that change seems like it would work against that.

If you think I'm missing something and that this is a bigger deal than I'm making it please don't hesitate to speak up, though!

**Comment by eoxford** [comment]
I think option 1 is fine for now. But yes, something to keep in mind if Crosshare expands/changes and it becomes more of an issue that "followers" can be anonymous. One thing that might be helpful even now though is to have somewhere on the page (is there a non-construction-related FAQ?) that addresses what someone should do if they have an issue with another user (repeated offensive comments or something). Presumably they should contact you, unless there is a more formal way to make a complaint. I agree I don't think this is likely to be an issue, but we don't have to wait until it becomes an issue before we have guidelines for dealing with it.

**Comment by mdirolf** [comment]
That is a great idea. The closest thing currently to a FAQ that isn't specific to the constructor is the "articles" linked from the bottom of the homepage. Maybe I should add a new one with that sort of info in it.

**Comment by mdirolf** [comment]
Added a new article here - https://crosshare.org/articles/reporting-offensive-comments - it should show up on the homepage within an hour or so. LMK if you have any suggestions or edits for the article text :)
