### ISSUE TITLE
"Newer puzzles" link on the constructor Dashboard

### ISSUE THREAD

**Issue by benchen71** [mdirolf/crosshare#384]
Feature request:

On the constructor Dashboard, in the Recent Puzzles section, have a "Newer puzzles" link appear after clicking "Older puzzles" so that you can go backwards and forwards through your constructed puzzles.

It is possible to do this with Featured puzzles on the Crosshare homepage. However, I've looked at the code and can see that the links are added differently.

**Comment by mdirolf** [comment]
Thanks for opening the issue! Definitely would like to do this but as you noticed it is a somewhat complicated task - might let it sit on the back-burner for a bit

**Comment by benchen71** [comment]
No worries. I'm much more keen to see [this issue](https://github.com/mdirolf/crosshare/issues/383) fixed.

**Comment by mdirolf** [comment]
This is awaiting deploy but should be live in the next couple of days or so, thanks to @drewrey

**Comment by benchen71** [comment]
Thanks so much for implementing this! I'm loving the ability to go forward and backwards through my puzzles!!
