### ISSUE TITLE
"Newer puzzles" on Constructor Dashboard

### ISSUE THREAD

**Issue by eoxford** [mdirolf/crosshare#396]
If you scroll down to the list of your puzzles on the Constructor Dashboard, the 8 most recent are displayed, and there's a hyperlink at the bottom that says "Older puzzles" that you can click on to see older ones. However, once you've navigated to your older puzzles, no "Newer puzzles" hyperlink appears, so there's no way to get back to the newer puzzles without reloading the page. (The URL doesn't change as you navigate through the puzzles, so hitting the Back button also won't work.) Could this feature be added?

**Comment by mdirolf** [comment]
Good idea 👍

**Comment by mdirolf** [comment]
This is awaiting deploy but should be live in the next couple of days or so, thanks to @drewrey

**Comment by eoxford** [comment]
Hooray! Thanks @mdirolf and @drewrey!
