### ISSUE TITLE
Keyboard size on small screens

### ISSUE THREAD

**Issue by datapolitical** [mdirolf/crosshare#397]
I just opened the site for the first time in a few months, and the keyboard seems to have receded to an almost unusable level.

I've included a screenshot of a normal iPhone 13 mini keyboard with the crosshare keyboard superimposed on top of it. 

There's also a ton of dead space where the clue goes, so there's no reason to have such a tiny keyboard.

I'm assuming this is the result of adapting the UI for larger phones but some of us still prefer smaller devices and the new layout is actively uncomfortable to the point of being unusable practically.

![image](https://user-images.githubusercontent.com/696957/214008799-ade0d268-0414-4e9f-af8d-5c3e905336cc.png)

![image](https://user-images.githubusercontent.com/696957/214008862-73582954-bf78-44b0-b69d-600d60967944.png)

**Comment by datapolitical** [comment]
Like, I would rather have the clue text be significantly smaller, and fit in like the size of two lines of small text, and have a full-size keyboard that I didn't have to think about where the buttons were going to be.

**Comment by mdirolf** [comment]
Thanks for the issue. I recognize the pain point - obviously in an ideal world the Crosshare keyboard would match exactly the virtual keyboard on whatever device you are using. Unfortunately the mobile os vendors (mainly ios tbh) make this extremely difficult. In some cases it appears to me that ios is deliberately hamstringing mobile web to get folks to publish apps through their store.

I too am a small phone user (iphone se currently), so I promise this isn't any preference for large devices going on. It's just that apple changes the layout of their keyboard with every release and also changes it across devices. Note that the actual button layout Crosshare shows is a very close match to their keyboard (it was an exact duplicate at one point, before they changed layouts), it's just that they have additional features above and below the text keys that cause things to shift. Also note that the Crosshare keyboard hasn't changed in > 1 year - so the change you're noting occurred on Apple's end.

I would say that the ideal solution here is #373. To be honest, though, that is probably going to have to wait for Apple to join the rest of the world in supporting the [virtual keyboard api](https://caniuse.com/mdn-api_virtualkeyboard)

**Comment by mdirolf** [comment]
Closing in favor of #373 - I'm not sure what improvements could be made here on our end given that the actual keyboard keys appear to be the exact same size as the native apple ones in your screenshot. I would love to make improvements but I don't see how they can be made w/o the virtual keyboard API at least giving us some info about what size the native keyboard is to match.

**Comment by datapolitical** [comment]
On all iPhones today, you could move the keyboard up to match the bottom location to the bottom row of the iOS keyboard.

Even if it wasn't a perfect match, making the zxcvbnm keys line up would be a major improvement. And you can definitely detect if people are using iPhones and adjust the keyboard location by vertical percentage.

You could also just make all the keys taller on iOS. Obviously, they're all shorter than iOS keys at the moment.

Like, the keyboard right now is smaller and in completely the wrong place, so any person using the website has to completely adjust their grip and balance, the phone differently.

I really appreciate you taking a look at this, I have a feeling that most of your iOS users would benefit.

**Comment by mdirolf** [comment]
There is still a lot of work to do to finish it up but I have made a lot of progress on native keyboard support. I encourage you to watch that issue as that will likely be the solution to this problem, too :)
